import { CallsCardProps } from "../types/CallsCardProps"
import dayjs from "dayjs"

export const callsDummyData: CallsCardProps[] = [
    {
        id: "call_001",
        senderName: "Arun",
        recevierName: "Karthik",
        peerId: "user_006",    
        roomId: "room_006",    
        isOnline: true,
        callType: "video",
        callStatus: "ended",
        createdAt: dayjs().toISOString(),
        time: dayjs().format("hh:mm A"),
    },
    {
        id: "call_002",
        senderName: "Meena",
        recevierName: "Arun",
        peerId: "user_001",    
        roomId: "room_007",    
        isOnline: false,
        callType: "audio",
        callStatus: "missed",
        createdAt: dayjs().subtract(2, "hour").toISOString(),
        time: dayjs().subtract(2, "hour").format("hh:mm A"),
    },
    {
        id: "call_003",
        senderName: "Rahul",
        recevierName: "Vikram",
        peerId: "user_005",    
        roomId: "room_008",   
        isOnline: true,
        callType: "video",
        callStatus: "ended",
        createdAt: dayjs().subtract(1, "day").toISOString(),
        time: dayjs().subtract(1, "day").format("hh:mm A"),
    },
    {
        id: "call_004",
        senderName: "Priya",
        recevierName: "Arun",
        peerId: "user_004",    
        roomId: "room_009",    
        isOnline: false,
        callType: "audio",
        callStatus: "missed",
        createdAt: dayjs().subtract(1, "day").subtract(3, "hour").toISOString(),
        time: dayjs().subtract(1, "day").subtract(3, "hour").format("hh:mm A"),
    },
    {
        id: "call_005",
        senderName: "Sanjay",
        recevierName: "Deepak",
        peerId: "user_007",    
        roomId: "room_010",    
        isOnline: true,
        callType: "video",
        callStatus: "ended",
        createdAt: dayjs().subtract(5, "day").toISOString(),
        time: dayjs().subtract(5, "day").format("DD MMM • hh:mm A"),
    },
    {
        id: "call_006",
        senderName: "Anitha",
        recevierName: "Arun",
        peerId: "user_001",    
        roomId: "room_011",    
        isOnline: false,
        callType: "audio",
        callStatus: "missed",
        createdAt: dayjs().subtract(1, "month").toISOString(),
        time: dayjs().subtract(1, "month").format("DD MMM • hh:mm A"),
    },
]